### ISSUE TITLE
Use sftp to replace file via formidble

### ISSUE THREAD

**Issue by JenneyJ** [mscdex/ssh2#617] opened 2017-09-30 17:32 UTC
Hi

This is more a question...,I use formidable to get selected file from the FS , I've file index.html (source) and different file that call index.html (target) and I want to override the target from the source `SSH SFTP lib`.

https://coligo.io/building-ajax-file-uploader-with-node/

form.on('file', function(field, file) {
    fs.rename(file.path, path.join(form.uploadDir, file.name));
});

Now after I got the file I need override the file for this specific path, `const writeStream = sftp.createWriteStream("/resources/index.html");`

is it possible ? I dont want to use the upload folder I just want to pick file from the FS and put it in specific path and override the original

**Comment by mscdex** [comment] 2017-09-30 18:14
I don't really understand what it is you're asking. You want to upload a file from an html form over sftp instead of moving it to a local directory? If that is what you're asking, then that should work just fine. You will just have to make sure to delete the (temporary) local copy after the file is successfully uploaded.

Also, you should try to use `sftp.fastPut()` to upload a local file as it will be faster due to parallel writes, which streams cannot use (by design).

**Comment by JenneyJ** [comment] 2017-09-30 20:56
HI,

Thank you very much for your quick answer.

what I did before I use the option to select a file with form using the file system (with formidable) 
**which works** I run node application in the cloud with express and user was able to select a file from his FS and upload it to replace some "old" file


`conn.on('ready', () => {
            conn.sftp((err, sftp) => {
                if (err) throw err;

      
                sftp.readdir("/app/", (err, list) => {
                    if (err) {
                        console.log("There is no directory:" + rootDir)
                    }
                    conn.end();
                })
              //read the file from app (instead the file system)
                const readStream = fs.createReadStream("./home.html");

                // This will wait until we know the readable stream is actually valid before piping
                readStream.on('open', () => {
                    console.log("open stream!");
                });

                // This catches any errors that happen while creating the readable stream (usually invalid names)
                readStream.on('error', (err) => {
                    console.log("Read file stream error: " + err);
                });

                const writeStream = sftp.createWriteStream("/resources/index.html");

                writeStream.on('close', () => {
                    console.log("Done");
                });

                writeStream.on('end', () => {
                    console.log("Connection closed");
                    conn.close();
                });

                writeStream.on('error', (err) => {
                    console.log("error: " + err);
                });
                //Here the file been transferred successfully
                readStream.pipe(writeStream);
`

Now I getting the file with this code (not with stream)

`    form.on('file', function(field, file) {
        console.log("the file is-> " + file);
    });`
  So here I need to get the file and use the fastPut method but how should I use it in my case ?
since I get the file from the event  and `sftp.fastPut()`  need the following which I dont have, only the remote path I have, **the file from localPath was already uploaded from the form ..**.
`localPath, remotePath, opts, cb`
From the code ...
`SFTPWrapper.prototype.fastPut = function(localPath, remotePath, opts, cb) {
  return this._stream.fastPut(localPath, remotePath, opts, cb);
};`
  Thanks a lot!!

**Comment by mscdex** [comment] 2019-07-08 18:45
For `formidable`, their documentation shows the available properties on `file`, including `.path` which contains the path of the uploaded file. Use that as the first argument to `fastPut()`.

**Closed by mscdex** 2019-07-08 18:45 UTC
Labels: question

**Comment by childrentime** [comment] 2022-02-24 16:13
formidable 1.0 can no longer be downloaded，So I had to use the 2.0 version. It only supports the filepath attribute
This is my code:
```typescript
  const form = formidable();
    form.parse(req, (err, fields, files) => {
        if (err) {
            res.end(err.message);
            return;
        }
        const id = fields!.id as string;
        const path = fields!.path as string;
        const file = files!.file as formidable.File;
        const ssh = clientMap.get(id)!;

        console.log(path, file);
        ssh?.sftp((err, sftp) => {
            if (err) {
                res.end(err.message);
            }
            sftp.fastPut(file.filepath, path, err => console.log(err));
        });
        res.end();
    });
```
it throw
`Error: Failure
    at 101 (D:\github\web-ssh\server\node_modules\ssh2\lib\protocol\SFTP.js:2617:19)
    at SFTP.push (D:\github\web-ssh\server\node_modules\ssh2\lib\protocol\SFTP.js:278:11)
    at CHANNEL_DATA (D:\github\web-ssh\server\node_modules\ssh2\lib\client.js:525:23)
    at 94 (D:\github\web-ssh\server\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
    at Protocol.onPayload (D:\github\web-ssh\server\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)  
    at GenericDecipherBinding.decrypt (D:\github\web-ssh\server\node_modules\ssh2\lib\protocol\crypto.js:1418:26)
    at Protocol.parsePacket [as _parse] (D:\github\web-ssh\server\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (D:\github\web-ssh\server\node_modules\ssh2\lib\protocol\Protocol.js:293:16)       
    at Socket.<anonymous> (D:\github\web-ssh\server\node_modules\ssh2\lib\client.js:713:21)
    at Socket.emit (events.js:375:28) {
  code: 4
}`

how to fix it

**Comment by mscdex** [comment] 2022-02-24 16:22
@childrentime You'll have to contact the server owner or debug on the server side if you have control of the server as the server is returning a generic failure, which could be the result of anything (e.g. disk full, bad permissions, etc.).
