### ISSUE TITLE
sftp.createReadStream won t trigger error on wrong file path

### ISSUE THREAD

**Issue by maboiteaspam** [mscdex/ssh2#267] opened 2015-05-11 09:09 UTC
Hi mscdex !

stfp.createReadStream behave unexpectedly when a file path of non existent file is used.

My case was
```
describe('sftp readFile', function(){
  this.timeout(10000);
  it('can read a file from remote', function(done){
    ssh.readFile(hostPwd, '~/.bashrc', function(err, data){
      data.should.match('whatever');
      done();
    });
  });
});
```

readFile being something like
```
// connect...
      var content = '';
      var streamErr;
      var stream = sftp.createReadStream(remoteFile);
      stream.on('data', function(d){
        content += ''+d;
      });
      stream.on('error', function(e){
        streamErr = e;
      });
      stream.on('close', function(){
        returnOrThrow(then, streamErr, content, server, conn);
      });
```

It is ending into a timeout every time, because ~/.bashrc can t be resolved appropriately when using the sftp layer.

I was thinking that binding error event would let me catch those errors to send them to the callback for post treatment, but error is not sent.

I can t say if it is possible to fix it, i was thinking to add, at least, a small note in ssh2-streams/sftp docs.

I suspect, but it is not yet confirmed, that sftp.createWriteStream behave the same.

**Comment by mscdex** [comment] 2015-05-11 16:03
The `error` event should be firing, the issue is that the `close` event was not firing properly. This is fixed in cf3465162e and in mscdex/ssh2-streams@875d63f0b2

**Comment by mscdex** [comment] 2015-05-11 16:06
Please try installing the `ssh2` master branch and it should also pick up the latest `ssh2-streams` with the changes. If that works, I'll publish a new `ssh2` version.

**Comment by maboiteaspam** [comment] 2015-05-12 01:36
wonderful ! Thanks a lot.

Feel bit of shame, i could have fixed it. Maybe next time, let s see.

Error returns appropriately now, with code 2 and meaningful message.

```js
  it('can properly fail to read a file from remote', function(done){
    ssh.readFile(hostPwd, '~/NoSuchFile', function(err, data){
      if(err) console.error(err);
      (!!err).should.be.true;
      err.code.should.eql(2);
      err.message.should.match(/No such file/);
      done();
    });
  });
```

Later i ll check stream writer too.

I let you close the ticket when it s fine.

**Closed** 2015-05-14 12:52 UTC
