### ISSUE TITLE
Make pagent.exe path configurable

### ISSUE THREAD

**Issue by Timmmm** [mscdex/ssh2#885] opened 2020-04-09 09:48 UTC
The path to `pagent.exe` (shouldn't it be `pageant.exe` btw?) is [hard-coded as](https://github.com/mscdex/ssh2/blob/master/lib/agent.js#L350):

    var EXEPATH = path.resolve(__dirname, '..', 'util/pagent.exe');

It would be nice if this were configurable, e.g. for use with Webpack and Electron where `__dirname` is unreliable and weird.

**Comment by rathboma** [comment] 2020-05-21 14:16
Ah, I'm having problems using the pageant ssh agent in my electron app. I wonder if this is why.

Going to experiment and figure out if that's true

**Comment by rathboma** [comment] 2020-05-21 20:25
@Timmmm see #894 . I'm fixing this for Electron use cases

**Comment by Daemoen** [comment] 2020-11-16 18:12
@Timmmm @rathboma (Not a developer, but guess I will take a stab at it) -- Unfortunately libssh including pageant mandatorily screws up gpg-agent providing pageant.  Any suggestions on how to go about handling this use case?  (pageant.exe is literally not used for gpg-agent pageant emulation)

**Comment by mscdex** [comment] 2021-05-29 06:48
Duplicate of https://github.com/mscdex/ssh2/issues/780.

**Closed by mscdex** 2021-05-29 06:48 UTC
