### ISSUE TITLE
Timeout waiting for handshake

### ISSUE THREAD

**Issue by corsmond** [mscdex/ssh2#855] opened 2019-11-20 05:25 UTC
I am getting the above error more often than not running on a Windows 10 machine connecting to and external sftp server.
Using the console "sftp" command I can connect every yime very quickly and list my folders, but using this modules I get a timeout waiting for handshake. I've increaded the timeout to 1 minute, but about 90% of the time it still times out, 
Running debug it gets stuck at DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP

ssh2: 0.8.6
node: 12.13.0

{
"host": "vltrader.supergrp.net",
"port": 22,
"username": "xxxxx",
"password": "xxxxxxxxxxxxxxx"
}

debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.6
debug1: Remote protocol version 2.0, remote software version Cleo VLTrader/5.6.1.0 SSH FTP server

**Comment by mscdex** [comment] 2019-11-20 12:55
Duplicate of #821.

**Closed by mscdex** 2019-11-20 12:55 UTC
