### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by gitloverr** [mscdex/ssh2#1022] opened 2021-06-14 16:54 UTC
hi everyone,

how to catch this error or solve??

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (.../node_modules/ssh2/lib/client.js:724:12)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```

my code snippet: 

```
const dump = () =>{

const conn = new Client()
return new Promise((resolve, reject) =>{
try {
    conn.on('ready', () => {
        console.log('Connected the Server!')
        conn.shell((err, stream) => {
          if (err) throw err
          stream.on('close', () => {
           console.log('Stream :: close')


          }).on('data', async(data) => {
            let receivedData = await data.toString().trim()
            }
          })
          stream.write(CMD)
        
        })
      }).connect({
        host: 'xxxx,
        port: xxx,
        username: 'xxx',
        privateKey: xxxxx
      })
} catch(err){

    res["result"]= 0
    res["data"]= null
    res["error"]= err 
    console.log(res,"********")
    return reject(res)
}
})
}

```

thank you

**Comment by mscdex** [comment] 2021-06-14 16:57
Is this a duplicate of https://github.com/mscdex/ssh2/issues/1018 ?

**Comment by gitloverr** [comment] 2021-06-15 08:13
hi @mscdex ,

I've tried it patch, but the problem continues...

**Comment by mscdex** [comment] 2021-06-15 13:33
If you enable debug output, what does it show?

**Closed** 2021-07-31 17:01 UTC
