### ISSUE TITLE
Interactive shell performance - slow

### ISSUE THREAD

**Issue by mkondath** [mscdex/ssh2#248] opened 2015-03-16 21:13 UTC
ssh2 with Node running Interactive shell is much slower than using a java ssh client to save device and network.

What would be some of the ways to improve performance ?

Thanks

**Comment by mscdex** [comment] 2015-03-16 22:02
Can you provide some more concrete information? How are you measuring performance? What node version? ssh2 module version? OS and version?

**Comment by mkondath** [comment] 2015-03-19 16:08
Brian

Specifically when data comes back from device is  there a way to get it in bigger chunks size ?

The java client let me do that.

Let me know if you need more info

Thanks

**Comment by mscdex** [comment] 2015-03-19 16:37
I do need more info, specifically the items I inquired about previously to start. I want something I can reproduce on my end.

**Comment by mkondath** [comment] 2015-03-19 20:00
Node version 0.12.0
OS – Osx 64 and Win 64
ssh2 version – latest ( 0.4.4)

My script


Connection = require('ssh2');


console.log('start test-ssh2 ');


var conn = new Connection();

conn.on('ready', function() {

  console.log('Connection :: ready');


  conn.exec('sh tech', function(err, stream) {

    if (err) throw err;

    stream.on('close', function() {

      console.log('Stream :: close');

      conn.end();

    }).on('data', function(data) {

      //console.log('STDOUT:**' + data+'**');

        console.log('data length:'+data.length);

    }).stderr.on('data', function(data) {

      console.log('STDERR: ' + data);

    });

   stream.end('dir \nexit\n');

  });

}).on('error', function(err) {

console.log('conn error ' + err );

}).connect({

  //debug: console.log,

  //host: 'swtg-1811',

  host: '172.18.194.56',

  port: 22,

  username: 'lab',

  password: 'lab'

});



Run timing below


See the 1st data chunk comes 2045 bytes and then the rest. Is there a way to increase that buffer size ?


time node test-ssh2

start test-ssh2

Connection :: ready


data length:2405

data length:8192

data length:8192

Stream :: close


real 0m2.006s

user 0m0.091s

sys 0m0.020s

**Comment by mscdex** [comment] 2015-03-19 21:22
A few things that should be noted:

1. In your example code you're not using an interactive shell *session*, but instead using `exec()` with what appears to be a script that starts a shell process. Are you sure that this is *exactly* what your java process is doing? If so, is it allocating a pty before executing the same command? Otherwise, your Java process could be using SFTP or something else to get a directory listing. If that is the case, `ssh2` supports fetching directory listings via SFTP as well.

2. Currently you are timing from process startup to process finish. This is not an accurate measure because there are many other things that happen before your `exec()` starts. Ideally you would use something like [`process.hrtime()`](https://nodejs.org/docs/latest/api/process.html#process_process_hrtime) right inside your `exec()` callback and then again inside the stream's `close` event handler, passing the timer value to get the elapsed time.

3. `ssh2` currently allows the server to send a *maximum* packet size of 32kb. The server is allowed to send any amount <= that value. It seems that in your example, the process you are running on the remote end is using an 8KB buffer.

It would be interesting to see detailed protocol-level output from your Java process to see exactly what it's using to execute the command (e.g. pty allocation or not, etc.).

**Comment by mkondath** [comment] 2015-03-23 20:47
Brian

I timed the data transfer using interactive shell on cisco router and it’s consistently coming in 8K buffer


buffer length :*459414*

Elapsed time (hr): 5s 311.016893ms

from linux machines, the buffers are coming in range of sizes   3k to few bytes. Not in a constant size I mean.

I don’t have java client source code, tying to figure out how its done there.

Thanks

**Comment by mscdex** [comment] 2015-03-23 22:32
FWIW you might try a utility like [this one](https://github.com/saironiq/mitmproxy) to MITM between the Java client and the Cisco router or any other SSH server. That may/may not be easier for you than trying to enable maximum debugging on both the client and server end to see exactly what is going on.

**Comment by AhmadKabakibi** [comment] 2015-07-08 07:24
is there an exmaple for interactive shell session i can keep write commands from consle and execute them in the current example with stream.end("ls -l \ncd / \nls") for example if i want to keep take the comands sperately not just one time how can i do that 

var Client = require('ssh2').Client;
var conn = new Client();
conn.on('ready', function() {
    console.log('Client :: ready');
    conn.shell(function(err, stream) {
        if (err) throw err;
        stream.on('close', function() {
            console.log('Stream :: close');
            conn.end();
        }).on('data', function(data) {
            console.log('STDOUT: ' + data);
        }).stderr.on('data', function(data) {
                console.log('STDERR: ' + data);
            });
        stream.end('ls -l\n');
    });
}).connect({
    host: 'IP',
    port: 22,
    username: 'username',
    password:'password',
    tryKeyboard: true
});

**Comment by mscdex** [comment] 2015-07-08 11:02
@AhmadKabakibi What you're asking isn't related to the original issue, but to answer your question, all you have to do is just continually write to the stream. For example: `stream.write('ls -l\n'); stream.write('uptime\n'); stream.write('exit\n');`

**Comment by AhmadKabakibi** [comment] 2015-07-08 11:14
Thanks for your answer @mscdex  .. sorry i wrote in wrong place my question isn't related to the original issue that's right.
i understand now how it's working :)

**Comment by mscdex** [comment] 2016-03-05 13:07
Closing this for now, without additional information and/or evidence there's not much I can do.

**Closed by mscdex** 2016-03-05 13:07 UTC
