### ISSUE TITLE
File resume is currently not supported

### ISSUE THREAD

**Issue by joneldiablo** [mscdex/ssh2#763] opened 2019-02-18 16:40 UTC
Hi, I'm having this error sometimes: "File resume is currently not supported". I have a recursive function which use ssh.putFile while upload many files:

```
const bubble = (track, i) => {
  let dir = sourceDirectoryName + '/' + newtrackname, resourcesDirectory + '/' + newtrackname;
  ssh.putFile(dir, fastPut)
    .then(function (success) {
          if ((i+1) < length) {
            i++;
            setTimeout(() => bubble(result[i], i), 100);
          }
    });
}
bubble(track[0],0);
```

**Comment by mscdex** [comment] 2019-02-18 16:43
Duplicate of https://github.com/mscdex/ssh2-streams/issues/118

**Closed by mscdex** 2019-02-18 16:43 UTC

**Comment by joneldiablo** [comment] 2019-02-18 17:16
so, this repo is the same ssh2-streams?

**Comment by unknownbrackets** [comment] 2019-02-18 17:24
No, but `putFile` seems to come from node-ssh, i.e. steelbrain/node-ssh#131.  It might help to give more detail when reporting issues, especially to a library you're not even using directly.

It seems the really, you're using `sftp.fastPut(` (indirectly):
https://github.com/steelbrain/node-ssh/blob/b02e8088f287f3ee2697f67ab94ec9fc4579f309/src/index.js#L208

"File resume is currently not supported" doesn't return any results on google, let alone in any of these repos.  My guess is it's probably coming from the ssh server you connected to, rather than from the library you're using to connect.  You may not be able to use `sftp.fastPut`.

-[Unknown]

**Comment by joneldiablo** [comment] 2019-02-19 15:48
thanks you so much, sorry for the inconvenience.
