### ISSUE TITLE
Prescribed / Documented way to execute commands on multiple servers in parallel 

### ISSUE THREAD

**Issue by timkelty** [mscdex/ssh2#436] opened 2016-06-09 11:31 UTC
Looking for a way to run commands in parallel against a pool of connections. Is there a way to do this with ssh2 out of the box?

Flightplan seems to achieve this using node-fibers: https://github.com/pstadler/flightplan/blob/master/lib/flight/remote.js

Also found:
https://github.com/maboiteaspam/ssh2-pool

Any advice would help, thanks!

**Comment by mscdex** [comment] 2016-06-09 11:59
There is no built-in way to do this with multiple connections. You can do multiplexing over a single connection (by design) of course, but that only gets you so far as that is subject to the server's max channel limits.

I personally do not have any experience with any modules that provide such functionality, so unfortunately I cannot really help you there.

**Comment by timkelty** [comment] 2016-06-09 12:02
Thanks for the reply, If I find a good solution, I'll post it here.

Ultimately I'm trying to achieve what this module does, except I want to use SSH2: https://github.com/shipitjs/ssh-pool

**Comment by mscdex** [comment] 2016-07-07 02:28
Closing this for now as this kind of thing is better done outside of this module since it is a more opinionated thing. If you found a module that worked well for you, feel free to post it here.

**Closed by mscdex** 2016-07-07 02:28 UTC
