### ISSUE TITLE
SFTPGo connection timeout event

### ISSUE THREAD

**Issue by mauriceleejy** [mscdex/ssh2#1033] opened 2021-07-07 10:27 UTC
Hello

I am testing a simple application which connects to a SFTPGo server (V2.1.0).

SFTPGo has a configuration parameter called "idle_timeout" which automatically closes idling connections (a single session is closed and not the whole connection)

`idle_timeout, integer. Time in minutes after which an idle client will be disconnected. 0 means disabled. Default: 15`

I did a few tests and this is what I observed:

1. If SFTPGo closes the connection due to idle timeout, the 'close', 'end', and 'error' event handlers do not fire off.

2. If SFTPGo service is stopped, the 'close' and 'end' event handlers are fired off.  

Any advice on how I can capture the 'connection closed' event due to idle timeout? 

My code is as follows:

```
var conn = new Client();
conn.on('ready', function() {
    conn.sftp(function(err, sftp) {
        if (err) console.log(err);

        sftp.readdir(remotePathToList, function(err, list) {
                if (err) console.log(err);
                console.dir(list);
        });

    });
}).on('error', () => {
    console.log('error');
}).on('end', () => {
    console.log(`end.`);
}).on('close', () => {
    console.log(`close.`);
}).connect(connection_settings);
```

**Comment by mscdex** [comment] 2021-07-07 13:27
Duplicate of https://github.com/mscdex/ssh2/issues/1032

**Closed by mscdex** 2021-07-07 13:27 UTC
