### ISSUE TITLE
cannot ssh into linux host based on a private key 'key' and a certificate 'key-cert.pub' 

### ISSUE THREAD

**Issue by bbthekings** [mscdex/ssh2#1176] opened 2022-05-05 14:35 UTC
I cannot find the function call to ssh into a linux host based on a private key 'key' and a certificate 'key-cert.pub' where the certificate is signed by a certification authority which is configured on the host as 'TrustedUserCAKeys /etc/ssh/user-ca-pubkey.pem'. Is this implemented or do I need to implement it by myself? If not implemented, how would you recommend to approach it? thanks

**Comment by mscdex** [comment] 2022-05-05 14:50
Duplicate of https://github.com/mscdex/ssh2/issues/551

**Closed by mscdex** 2022-05-05 14:50 UTC
