### ISSUE TITLE
fastPut callback is not being executed

### ISSUE THREAD

**Issue by mark-rodgers** [mscdex/ssh2#947] opened 2020-10-27 18:52 UTC
## Environment

NodeJS: v14.5.0
ssh2: 0.8.9

## Code Example

```javascript
const ssh2 = require("ssh2");

const src = "/home/mark-rodgers/0102449171338.wav";
const dest = "20Oct27/0102449171338.wav";
const conn = new ssh2.Client();

conn.on("error", err => {
  console.log(err);
});

conn.on("ready", () => {
  console.log("connected!");
  conn.sftp((err, sftp) => {
    if (err) return;
    console.log(1);
    sftp.fastPut(src, dest, { }, err => {
      console.log(2); // file does upload, but this callback function never executes
    });
    console.log(3);
  });
});

conn.connect({ 
  host: "...",
  port: "...",
  username: "...",
  password: "..."
});
```

## Output
```
connected!
1
3
```

## Expected Result
The file does upload but the callback never gets executed, so there is no way for me to know when the upload is complete, if it was successful, or if there was an error.
```
connected!
1
2
3
```

**Comment by mark-rodgers** [comment] 2020-10-27 19:01
UPDATE: everything works as expected in Node v12.19.0

**Comment by mscdex** [comment] 2020-10-28 02:33
Out of curiosity, would you mind testing (do not use this in production until its released though) the master branch of ssh2 with your transfer and see if the same problem still exists? There have been some big changes in there recently that may impact issues like this.

**Comment by mark-rodgers** [comment] 2020-10-28 16:28
Tested again using Node v14.5.0 with the master branch of ssh2 and everything worked as expected.

```bash
npm uninstall ssh2
npm install mscdex/ssh2#master
```

**Comment by fengxinming** [comment] 2020-12-04 01:49
I met the same problem on node v14.15.1

**Comment by mscdex** [comment] 2020-12-04 02:00
@fengxinming with the master branch or the current version on npm?

**Comment by fengxinming** [comment] 2020-12-04 14:40
@mscdex Both are not working on node v14.15.1

**Comment by mscdex** [comment] 2020-12-04 17:41
@fengxinming and with node v12.x?

**Comment by fengxinming** [comment] 2020-12-05 03:19
@mscdex It can work on node v12.x

**Comment by theophilusx** [comment] 2020-12-11 07:07
Interesting. This is NOT working for me using master branch and node v12.20.0. It appears to work for small files, but hangs for larger files. The same code with ssh2 0.8.9 and node v12.20.0 works fine. This seems to be an issue with the concurrency of fastPut(). If I set concurrency: 1 it works. I have attached two logs, one success.txt and one fail.txt which shows the two different outputs using master branch. I have also included my test file.  The code I'm using is

````js
'use strict';

// A low level simple fastput script which only uses the underlying
// ssh2 and sftpstreams libraries. Used to isolate issues which may be
// specific to the underlying module libraries from the module itself.

// Put credentials in .env file in repo root and then call the script with
// 2 args src and dst. Script will upload src to dst on remote server.

const path = require('path');
const dotenvPath = path.join(__dirname, '..', '.env');

require('dotenv').config({path: dotenvPath});

const {Client} = require('ssh2');

const config = {
  host: process.env.SFTP_SERVER,
  username: process.env.SFTP_USER,
  password: process.env.SFTP_PASSWORD,
  port: process.env.SFTP_PORT || 22,
  debug: (msg) => {
    console.log(msg);
  }
};

const options = {
  //mode: 0o777,
  //chunkSize: 32768,
  // concurrency: 1,
  // step: function(total_transferred, chunk, total) {
  //   console.log(
  //     `Total Transferred: ${total_transferred} Chunk: ${chunk}` +
  //       ` Total: ${total}`
  //   );
  // }
};

const src = process.argv[2];
const dst = process.argv[3];

let client = new Client();

client.on('ready', () => {
    client.sftp((err, sftp) => {
      if (err) {
        console.error(`SFTP Error: ${err.message}`);
      } else {
        console.log(`Transferring ${src} to ${dst}`);
        sftp.fastPut(src, dst, options, (err) => {
          if (err) {
            console.error(`fastPut Error: ${err.message}`);
          } else {
            console.log('File uploaded');
          }
          client.end();
        });
      }
    });
  }).on('error', function(err) {
    console.error(err.message);
  }).on('end', () => {
    console.log('End event fired');
  }).on('close', () => {
    console.log('Close event fired');
  }).connect(config);
````
[fail.txt](https://github.com/mscdex/ssh2/files/5677522/fail.txt)
[success.txt](https://github.com/mscdex/ssh2/files/5677523/success.txt)
[test-file2.txt](https://github.com/mscdex/ssh2/files/5677526/test-file2.txt)

**Comment by pataar** [comment] 2020-12-16 16:06
Same problem here

**Comment by mscdex** [comment] 2020-12-20 04:12
Anyone encountering the hanging with `fastPut()` with the master branch, can you please update the branch and try again? I believe the issue may be fixed now.

**Comment by theophilusx** [comment] 2020-12-20 07:24
Just did a very quick run of my tests and while the fastput/fastget
tests seemed to have now passed, many other tests which were previously
passing are now failing. Will need to dig further. However, noticed some
very unusual error messages (note that with previous version, all tests
were passing except the fastPut/fastGet) This was all run under node
v12.20.0 e.g.

     Uncaught Error: error:00000000:lib(0):func(0):reason(0)
      at AESGCMDecipher.decrypt (<anonymous>)
      at AESGCMDecipherBinding.decrypt (node_modules/ssh2/lib/protocol/crypto.js:1074:22)
      at Protocol.parsePacket [as _parse] (node_modules/ssh2/lib/protocol/Protocol.js:1938:25)
      at Protocol.parse (node_modules/ssh2/lib/protocol/Protocol.js:287:16)
      at Socket.<anonymous> (node_modules/ssh2/lib/client.js:644:13)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

and

    Uncaught Error: Packet length 65513 exceeds max length of 34000
      at doFatalSFTPError (node_modules/ssh2/lib/protocol/SFTP.js:2332:15)
      at SFTP.push (node_modules/ssh2/lib/protocol/SFTP.js:213:18)
      at CHANNEL_DATA (node_modules/ssh2/lib/client.js:519:23)
      at 94 (node_modules/ssh2/lib/protocol/handlers.misc.js:841:16)
      at Protocol.onPayload (node_modules/ssh2/lib/protocol/Protocol.js:1969:10)
      at AESGCMDecipherBinding.decrypt (node_modules/ssh2/lib/protocol/crypto.js:1089:26)
      at Protocol.parsePacket [as _parse] (node_modules/ssh2/lib/protocol/Protocol.js:1938:25)
      at Protocol.parse (node_modules/ssh2/lib/protocol/Protocol.js:287:16)
      at Socket.<anonymous> (node_modules/ssh2/lib/client.js:644:13)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

and multiple errors which look like they are related to
readStream/writeStream and the done() method being called multiple
times, which could be something in my module, but on the whole, we just
use pip() with streams. e.g.

     done() called multiple times in test <get() method tests get large text file using a stream> of file /home/tim/git/ssh2-sftp-client/test/12get.js; in addition, done() received error: Error: get: No response from server /home/tim/testServer/get-large.txt
    at Object.formatError (/home/tim/git/ssh2-sftp-client/src/utils.js:57:18)
    at ReadStream.<anonymous> (/home/tim/git/ssh2-sftp-client/src/index.js:397:19)
    at Object.onceWrapper (events.js:421:26)
    at ReadStream.emit (events.js:314:20)
    at /home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/SFTP.js:3272:12
    at Object.cb (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/SFTP.js:438:20)
    at cleanupRequests (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/SFTP.js:2352:11)
    at doFatalSFTPError (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/SFTP.js:2331:3)
    at SFTP.push (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/SFTP.js:213:18)
    at CHANNEL_DATA (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/client.js:519:23)
    at 94 (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/handlers.misc.js:841:16)
    at Protocol.onPayload (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/Protocol.js:1969:10)
    at AESGCMDecipherBinding.decrypt (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/crypto.js:1089:26)
    at Protocol.parsePacket [as _parse] (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/Protocol.js:1938:25)
    at Protocol.parse (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/protocol/Protocol.js:287:16)
    at Socket.<anonymous> (/home/tim/git/ssh2-sftp-client/node_modules/ssh2/lib/client.js:644:13)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {

I will try and dig in further tomorrow and provide more detail if
possible.

**Comment by mscdex** [comment] 2020-12-20 17:54
I'm not able to reproduce those errors with the master branch `ssh2` tests on node v10.x/v12.x/v14.x. Let me know if you are able to come up with simplified, reproducible test cases.

**Comment by mscdex** [comment] 2020-12-20 18:13
I just pushed some changes to the crypto binding that might help with the OpenSSL error issue -- it should at least show the real error message instead of the "no error" message.

**Comment by theophilusx** [comment] 2020-12-21 19:54
OK, that fix seems to have addressed one of the errors. I'm seeing unusual errors with sftp.createReadStream, but not sure if your re-write has completed the stream stuff yet? Also not sure if you want this logged as a separate issue or not?

The code I'm using, which works in 0.8.9 is generating the following errors

````
Client ready event fired
Read Error: No response from server
Client Error: Packet length 65545 exceeds max length of 34000
Client Error: Bad packet length: -1949144854
Client end event fired
Client close event fired
Read Error: No response from server
````

The code I'm using is as follows

````js
'use strict';

const path = require('path');

const dotenvPath = path.join(__dirname, '..', '.env');

require('dotenv').config({path: dotenvPath});

const {Client} = require('ssh2');
const fs = require('fs');

const config = {
  host: process.env.SFTP_SERVER,
  username: process.env.SFTP_USER,
  password: process.env.SFTP_PASSWORD,
  port: process.env.SFTP_PORT || 22
};

const client = new Client();

const remotePath = process.argv[2];
const localPath = process.argv[3];

client
  .on('ready', function () {
    console.log('Client ready event fired');
    client.sftp(function (err, sftp) {
      if (err) {
        console.log(`SFTP Error: ${err.message}`);
      } else {
        let sout = fs.createWriteStream(localPath);
        let sin = sftp.createReadStream(remotePath);
        sout.on('error', (err) => {
          console.error(`Write Error: ${err.message}`);
        });
        sin.on('error', (err) => {
          console.error(`Read Error: ${err.message}`);
        });
        sout.on('finish', () => {
          console.log('File dowwload complete');
          console.log('Closing client connection');
          client.end();
        });
        sin.pipe(sout);
      }
    });
  })
  .on('error', function (err) {
    console.error(`Client Error: ${err.message}`);
  })
  .on('end', () => {
    console.log('Client end event fired');
  })
  .on('close', () => {
    console.log('Client close event fired');
  })
  .connect(config);
````

**Comment by mscdex** [comment] 2021-05-02 00:30
@theophilusx If you're still experiencing this with the current `ssh2` master branch, please open a new issue.

**Comment by mscdex** [comment] 2021-05-02 00:33
@mark-rodgers @fengxinming @pataar Just so I know where things currently stand, are any of you still experiencing this issue with the current `ssh2` master branch?

**Comment by theophilusx** [comment] 2021-05-02 07:05
@mscdex No 'duplicate' errors, seems to be working well now. All my tests are now passing
with no errors. The re-write is looking good from the SFTP perspective.

Tested against node versions 12.22.1, 13.14.0, 14.16.1, 15.14.0 and
16.0.0

thanks for all the hard work you have done in moving this rewrite
forward.

**Comment by pataar** [comment] 2021-05-04 12:11
Seems to work!

**Closed** 2023-06-21 20:29 UTC
