### ISSUE TITLE
Can not established ssh connection via private key

### ISSUE THREAD

**Issue by EVINK** [mscdex/ssh2#1265] opened 2023-01-21 05:36 UTC
I try to connect with option ```password``` and it works good, but once I changed to ```privateKey```, it hints me 'All configured authentication methods failed'

```js
const ssh2 = require('ssh2')
let conn = new ssh2.Client()
conn.on('ready', () => {
    console.log('on ready')
}).connect({
    host: '127.0.0.1',
    port: 22,
    username: 'evink',
    privateKey: require('fs').readFileSync('/Users/evink/.ssh/id_rsa')
})
```

output: 
```sh
Inbound: Received USERAUTH_FAILURE (publickey,password,keyboard-interactive)
Client: none auth failed
authMethods >> [ 'publickey', 'password', 'keyboard-interactive' ]
curPartial >> null
Outbound: Sending USERAUTH_REQUEST (publickey -- check)
Inbound: Received USERAUTH_FAILURE (publickey,password,keyboard-interactive)
Client: publickey auth failed
authMethods >> [ 'publickey', 'password', 'keyboard-interactive' ]
curPartial >> false
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at doNextAuth (/Users/evink/workspace/project-x/node_modules/ssh2/lib/client.js:806:21)
    at tryNextAuth (/Users/evink/workspace/project-x/node_modules/ssh2/lib/client.js:996:7)
    at USERAUTH_FAILURE (/Users/evink/workspace/project-x/node_modules/ssh2/lib/client.js:376:11)
    at 51 (/Users/evink/workspace/project-x/node_modules/ssh2/lib/protocol/handlers.misc.js:342:16)
    at Protocol.onPayload (/Users/evink/workspace/project-x/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
    at ChaChaPolyDecipherBinding.decrypt (/Users/evink/workspace/project-x/node_modules/ssh2/lib/protocol/crypto.js:851:26)
    at Protocol.parsePacket [as _parse] (/Users/evink/workspace/project-x/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
    at Protocol.parse (/Users/evink/workspace/project-x/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
    at Socket.<anonymous> (/Users/evink/workspace/project-x/node_modules/ssh2/lib/client.js:716:21)
    at Socket.emit (node:events:394:28)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/Users/evink/workspace/project-x/node_modules/ssh2/lib/client.js:718:20)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  level: 'client-authentication'
}
```

Any help will be appreciated

-------------

Module ssh2 version: ^1.11.0
Node version: v16.6.2
Platform: macOs Ventura

**Comment by mscdex** [comment] 2023-01-21 06:47
Do you have evidence that the same key is actually working with another SSH client? If it works with say the OpenSSH client, you might add `-vvv` to the OpenSSH client command line and verify that it is in fact using that key and only that key for authentication.

**Comment by EVINK** [comment] 2023-01-21 07:19
```sh
 ssh evink@127.0.0.1 -vvv
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/evink/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug2: resolve_canonicalize: hostname 127.0.0.1 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/evink/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/evink/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug3: ssh_connect_direct: entering
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x48
debug1: Connection established.
debug1: identity file /Users/evink/.ssh/id_rsa type 0
...
```

I have another VPS and I disabled password authentication for it 

```
# /etc/ssh/sshd_config
...
PasswordAuthentication no
...
```

**Comment by mscdex** [comment] 2023-01-21 09:39
Judging by your node script output, it doesn't seem to match the code you've provided. Are you actually passing an `authHandler` in your connection config?

**Comment by EVINK** [comment] 2023-01-21 09:53
> Judging by your node script output, it doesn't seem to match the code you've provided. Are you actually passing an `authHandler` in your connection config?

No, I don't pass any other params to it. 

I just create a new project which only includes module ssh2 and the code above

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/14816851/213861585-a80ce23a-8489-4252-bce7-db1ea7a90382.png">

**Comment by mscdex** [comment] 2023-01-21 16:25
What is the ident string of the server or what server and server version are you connecting to?

Also what node version are you using on the client side?

**Comment by Krenodeno** [comment] 2023-01-23 17:26
Hi,
I'm currently facing the same issue. After some tests, it looks like a minimal reproducible example is connecting to an Ubuntu 22.04 host, using a RSA based key with the minimal code EVINK provided. Not sure why yet, but I felt you could use this piece of info.

**Comment by mscdex** [comment] 2023-01-23 17:51
If it's an RSA key, it's probably https://github.com/mscdex/ssh2/issues/989.

**Comment by mscdex** [comment] 2023-04-29 23:34
The aforementioned fix has now been committed and will be in a release soon. If you are still encountering the same issue after the fix, let me know.

**Closed by mscdex** 2023-04-29 23:34 UTC
