### ISSUE TITLE
Is there a way to read the config from $HOME/.ssh/config?

### ISSUE THREAD

**Issue by acroca** [mscdex/ssh2#261] opened 2015-04-30 15:57 UTC
I'm sorry if this question has been asked before, but I couldn't find an answer anywhere.
I use that file to configure ssh access across machines.
Is there a way to read the config from that file in the same way `ssh` command does?

**Comment by mscdex** [comment] 2015-04-30 16:54
This is a duplicate of #70.

**Closed by mscdex** 2015-04-30 16:54 UTC
