### ISSUE TITLE
Implementation of SFTP STAT command

### ISSUE THREAD

**Issue by boonware** [mscdex/ssh2#949] opened 2020-10-29 10:04 UTC
My SFTP client application is receiving the following error:

```
{ Error: No such file
    at SFTPStream._transform (/opt/foo/bar/src/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/opt/foo/bar/src/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
```

Since there is no further context info logged (for example, file name), I am not fully sure of the cause, but it appears to occur during a call to the [stat](https://github.com/mscdex/ssh2/blob/master/SFTP.md#sftp-methods) method on the root directory.

How is "stat" implemented? If I manually log in to my SFTP server and execute "stat" on the CLI I receive "invalid command".

**Comment by mscdex** [comment] 2020-10-29 11:15
Duplicate of https://github.com/mscdex/ssh2/issues/948

**Closed by mscdex** 2020-10-29 11:15 UTC
