### ISSUE TITLE
Keepalive timeout

### ISSUE THREAD

**Issue by NuSkooler** [mscdex/ssh2#367] opened 2015-12-08 04:35 UTC
I am using `ssh2` for SSH connections to a BBS system I've been working on. Popular BBS clients such as SyncTerm and EtherTerm randomly (it seems) disconnect. Debug output shows `Error: Keepalive timeout`
- [SyncTerm](http://syncterm.bbsdev.net/) does this quite quickly -- 20-30 seconds max of being online
- [EtherTerm](https://github.com/M-griffin/EtherTerm) (libssh based I believe) takes much longer (a couple minutes generally)
- Linux `ssh` does not seem to have this issue

Below is the last bit of a log from my BBS. `ssh2` debug information is passed through my Bunyan log (prefixed with "SSH"):

```
[2015-12-08T04:25:51.062Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing CHANNEL_DATA (43)
[2015-12-08T04:25:51.062Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing CHANNEL_DATA (43)
[2015-12-08T04:25:51.063Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing CHANNEL_DATA (43)
[2015-12-08T04:25:51.063Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing CHANNEL_DATA (43)
[2015-12-08T04:25:51.063Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing CHANNEL_DATA (43)
[2015-12-08T04:25:52.755Z]  WARN: ENiGMA½ BBS/28282 on nu-freya: SSH connection error (clientId=0, error="Error: Keepalive timeout")
[2015-12-08T04:25:52.755Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
[2015-12-08T04:25:52.760Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing CHANNEL_EOF (43)
[2015-12-08T04:25:52.760Z] TRACE: ENiGMA½ BBS/28282 on nu-freya: SSH: [122914.388161123] DEBUG: Outgoing: Writing CHANNEL_CLOSE (43)
```

The SSH server implementation itself can be found on Github here: https://github.com/NuSkooler/enigma-bbs/blob/master/core/servers/ssh.js

**Comment by mscdex** [comment] 2015-12-08 05:21
Typically that means the client isn't responding to global requests for some reason. The server always requests a reply, so even if it doesn't explicitly support the `keepalive@openssh.com` global request, it should still reply with a failure response which is just as good as a success response because it means the connection is still good.

I'm not familiar with SyncTerm or EtherTerm, but libssh/libssh2 should be decent implementations, so I wouldn't really expect those libraries to not respond. Do these clients have debug modes that spit out low-level debug information?

**Comment by NuSkooler** [comment] 2015-12-08 22:09
@mscdex: EtherTerm always has a debug window open, but if it's verbose enough to tell you what you need to know I'm not sure. I can supply a log if that would help.

SyncTERM may have the ability, but I'm unfamiliar with how to make it work.

**Comment by mscdex** [comment] 2015-12-09 00:14
If you can provide me with debug logs from these clients that would be great.

**Comment by NuSkooler** [comment] 2015-12-09 06:08
Here are a couple logs:
* First is from a debug build of EtherTerm @ http://pastebin.com/qPLD1CKm
* Second is from ENiGMA½ side of things for the same session: http://pastebin.com/Bk39EQV4

Hopefully that helps in some way. Another thing I could do is punch a hole in the firewall if you'd like to connect and try it out. Perhaps is in the way I'm using `ssh2`. ...or of course if there is anything else I can provide.

**Comment by NuSkooler** [comment] 2015-12-09 06:11
Just noticed this, looks interesting: https://github.com/rbann/ssh2/commit/020c365605e3dac9fe02ee1035ce6171905bd488

**Comment by mscdex** [comment] 2015-12-09 06:40
It looks like the server isn't automatically sending the global keepalive request like it should be. Probably a bug in the keepalive manager somewhere.

**Comment by rbann** [comment] 2015-12-09 12:45
@NuSkooler Could you please send the full `ssh2` debug log? I did not have issues with the keepalive manager. I can have a look if the server really sends the keepalive request and weather the client responds to them correctly.

The relevan log messages:
```
DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
```
and
```
DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE
```

**Comment by NuSkooler** [comment] 2015-12-09 16:25
@rbann the log is fairly long so pastebin/etc. didn't like it. Here is a link to compressed version: http://s000.tinyupload.com/index.php?file_id=63993543015028678950

This is a full ENiGMA½ session via EtherTerm

**Comment by mscdex** [comment] 2015-12-09 16:34
Ah ok, so the client is sending back an unimplemented message instead of a failure response. The keepalive logic should probably be tweaked so that the timestamp is reset every time we get any kind of message from the client.

**Comment by NuSkooler** [comment] 2015-12-09 16:48
Ah this makes sense, I'll take a peek at the log during a SyncTERM session tonight -- I'm guessing it's a similar situation.

**Comment by rbann** [comment] 2015-12-09 18:42
@mscdex Note that if in the future the server will be able to send global requests other than keepalive, these clients will cause the server to keep adding global-request-reply-callbacks indefinitly.

**Comment by mscdex** [comment] 2015-12-09 19:05
@rbann Yep, will need to keep track of sequence numbers for matching up unimplemented messages. PRs welcome ;-)

**Comment by rbann** [comment] 2015-12-10 08:45
I'm looking into the tests and will do that. Btw, you are not having a `.gitignore` file. Is it intentional?

**Comment by NuSkooler** [comment] 2015-12-10 15:39
If there is anything I can do to help please let me know. I'm afraid I'm not super familiar with the inner workings of the SSH protocol, but I'll do what I can!

**Comment by mscdex** [comment] 2015-12-10 15:52
@NuSkooler If you want, you can try the changes I recently pushed: `npm install https://github.com/mscdex/ssh2/tarball/master` and then change to `./node_modules/ssh2` and do `npm install https://github.com/mscdex/ssh2-streams/tarball/master`.

**Comment by NuSkooler** [comment] 2015-12-10 22:09
@mscdex Here is a couple logs after performing the steps to update to master: http://s000.tinyupload.com/index.php?file_id=24800535784155454428

Both terminals still fail fairly quickly.

**Comment by NuSkooler** [comment] 2015-12-14 16:43
@mscdex or @rbann, any idea what to try next?

**Comment by rbann** [comment] 2015-12-14 16:59
Hi,

All I could do is modifying client's code on a local checkout to behave
like your clients (sending UNIMPLEMENTED on global requests), but with
Brian's modification everythimg worked as expected.
Are you sure you are using the latest master for both ssh2 and ssh2-streams?
R

**Comment by mscdex** [comment] 2015-12-14 17:39
@NuSkooler Unfortunately, I haven't had time to test with those ssh clients yet.

**Comment by NuSkooler** [comment] 2015-12-16 05:27
@rbann I followed the steps above to update & didn't receive any errors. I should have a chance to try again tomorrow on a clean checkout.

@mscdex I understand being busy, I'm just eager!

**Comment by NuSkooler** [comment] 2015-12-18 05:34
@rbann OK, I tried again tonight on a different box. Here is the cut + paste log from my terminal following your steps. I then restarted node / my application & tried again with SyncTERM. I ended up with it losing the connection again after about a minute or so.

```shell
nuskooler@nu-freya ~/d/enigma-bbs> npm install https://github.com/mscdex/ssh2/tarball/master
npm WARN package.json pty@0.0.0 No README data
ssh2@0.4.12 node_modules/ssh2
├── readable-stream@1.0.33 (inherits@2.0.1, string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.2)
└── ssh2-streams@0.0.19 (streamsearch@0.1.2, asn1@0.2.3)
nuskooler@nu-freya ~/d/enigma-bbs> cd node_modules/
nuskooler@nu-freya ~/d/e/node_modules> cd ssh2
nuskooler@nu-freya ~/d/e/n/ssh2> npm install https://github.com/mscdex/ssh2-streams/tarball/master
ssh2-streams@0.0.19 node_modules/ssh2-streams
├── streamsearch@0.1.2
└── asn1@0.2.3
nuskooler@nu-freya ~/d/e/n/ssh2>
```

**Comment by soichih** [comment] 2016-09-06 14:28
I am not sure if it's related to but I am seeing a similar error message.

```
error: ssh connection error
error:  Error: Keepalive timeout
    at sendKA (/usr/local/sca-wf/node_modules/ssh2/lib/client.js:255:19)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

According to /ssh2/lib/client.js, "Keepalive timeout" is raised whenever it reaches the max keepalive retry.

```
    if (++kacount > kacountmax) {
      clearInterval(katimer);
      if (sock.readable) {
        var err = new Error('Keepalive timeout');
        err.level = 'client-timeout';
        self.emit('error', err);
        sock.destroy();
      }
      return;
    }

```

If I don't set the keepaliveCountmax via the configuration, it defaults to just 3.

```
  this.config.keepaliveCountMax = (typeof cfg.keepaliveCountMax === 'number'
                                   && cfg.keepaliveCountMax >= 0
                                   ? cfg.keepaliveCountMax
                                   : 3);
```

My questions are..

1) Why does it even have a *max* keepalive? 
2) Why does it have to emit an *error* when it reaches the max? I think "end" or "close" event will be more appropriate. "client-timeout" also seems like a wrong error level. 
3) How can I configure it so that it will try keep alive forever? (I'd like to avoid setting it to something like 999999999..)

Thank you!!

**Comment by mscdex** [comment] 2016-09-06 14:51
@soichih 

1. Because there needs to be some threshold to determine how many unanswered requests constitutes a dead connection. If you set this too low you could cause a valid connection to closed early (e.g. the server could just be temporarily overloaded). If you set this too high then you could end up waiting a long time if the connection really is dead (e.g. remote server abruptly stopped, local network connection disconnected, etc.). The number of unanswered "pings" gets reset to 0 whenever we see a response from the server.

Right now the situation for the client implementation could be improved a bit by resetting keepalive on receipt of *any* packet (not just a response to "ping" requests). This is actually what the server implementation's keepalive mechanism already does.

2. It emits 'error' because otherwise you'd have no way of knowing that the connection is being terminated abnormally. This is similar to other abnormal (TCP-level) connection issues such as connection timeouts, unexpected connection resets, etc. You should still receive a `'close'` event though, since the socket is destroyed after the `'error'` event is emitted.

3. It's not clear what you're asking for here. Setting high maximum (as explained in my first point) keepalive settings (both counts and intervals) can lead to excessively long wait times when there *is* a dead connection. The whole reason for this keepalive mechanism is to allow for configurable (shorter) connection timeouts, since the default TCP keepalive timeouts on all operating systems are set to very high values and node currently does not expose the necessary OS APIs to fine tune the TCP keepalive settings (IIRC this is mostly because not all platforms -- or kernel versions in the case of *nix -- expose such APIs).

**Comment by soichih** [comment] 2016-09-06 15:08
@mscdex 

Ah, I see.. I didn't realize that kacount was reset when keepalive is successfully sent. I also didn't know that keepalive was used as a mechanism to detect dead connection. Thanks for the explanation. 

So, for my error message, it's really caused by a server not responding to my ping? I will have to investigate..

**Comment by mscdex** [comment] 2016-09-06 15:12
@soichih Yes, the keepalive mechanism is there mainly to detect dead connections. It works more or less exactly the way the OpenSSH does. If you are receiving keepalive timeouts, you may look to see if it's a server issue or if the `ssh2` keepalive settings need to be tweaked a bit for that particular server (e.g. a very busy server or a slow server due to running on resource-constrained hardware for example).

**Comment by Kurtas** [comment] 2018-10-17 09:36
HI @mscdex 
I'm trying to resolve that Cisco ASA end the session, but the data still comming to the client.

I figured out that SSH protocol has timeout what is raised, when the client don't send any data, no matter if client still receiving data.

So I tried to use following settings in connection method
`{keepaliveCountMax: 10, keepaliveInterval: 1500}`

See attached debug log where I extract only outgoing communication, as you can see client don't send KeepAlive ping when stream still receiving data. There is only one ping and it's 1min after what command was sent.  The server has set timeout 1min.
```
// Command sent - long output
[Tue Oct 16 2018 17:16:58 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_DATA (3) 
[Tue Oct 16 2018 17:17:09 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (3, 524310)
[Tue Oct 16 2018 17:17:33 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (3, 524355)
[Tue Oct 16 2018 17:17:57 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:05 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (3, 524365)

//Incoming data stopped to flow
[Tue Oct 16 2018 17:18:30 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:31 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:33 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:34 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:36 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:37 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:39 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:40 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:42 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[Tue Oct 16 2018 17:18:43 GMT+0200 (CEST)] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
```

**So first question is, Is this behavior expected or it's bug? I think that's a bug, KeepAlive ping should be sended periodically.**

Then I found out that Cisco ASA doesn't support SSH noop packet (sometimes called null packet) and that I have to send some character to keep connection alive. (tried with the putty)
I'm using `shell` method to create `sshStream` where I write a command, then listen on data. So I just add an interval which call `write` with backspace character every 1.5s
But the result is same. Only 1 outgoing data, during almost 2 minutes. I also tried to use exec method to write backspace character but it's same.

Here is the part of code and logs

```
this.ssh.shell({rows: 150, cols: 250, term: 'vt100'}, {}, (err, stream) => {
        if (err) return reject(new ABConnectionError(err));
        if (stream === false) {
          this.emit('log', 'stream false');
          this.ssh.once('continue', () => resolve(this._iShell()));
        } else {
          this.shellStream = stream;
          if (this.keepAliveInterval) clearInterval(this.keepAliveInterval);
          this.keepAliveInterval = setInterval(() => {
            if (stream.writable) {
              stream.write('\b');
              console.log(`KeepAlive ping`);
            }
          }, 1500);
          stream.once('close', () => {
            this.shellStream = null;
          });
          stream.on('error', e => this.emit('log', `iShell stream error ${e}`));
          stream.on('data', data => this.receiveData(data));
        }
      });//ssh.shell
```

```
//Command sent
[Wed Oct 17 2018 11:16:12 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_DATA (3)
[Wed Oct 17 2018 11:16:21 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (3, 524335)
[Wed Oct 17 2018 11:16:41 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (3, 524355)
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_DATA (3)
KeepAlive ping
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: IN_PACKETDATA
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: Decrypting
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: HMAC size:20
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: IN_PACKETDATAVERIFY
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: Verifying MAC
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[Wed Oct 17 2018 11:17:05 GMT+0200 (CEST)] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[Wed Oct 17 2018 11:17:12 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (3, 524364)
//Incoming data stopped to flow => server closed connection
[Wed Oct 17 2018 11:17:52 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (3, 524346)
[Wed Oct 17 2018 11:17:52 GMT+0200 (CEST)] DEBUG: Outgoing: Writing CHANNEL_DATA (3)
KeepAlive ping


// Cisco ASA log 
Oct 17 2018 11:16:11: %ASA-6-302013: Built inbound TCP connection 3100 for inside:192.168.11.171/57392 (192.168.11.171/57392) to identity:192.168.110.29/22 (192.168.110.29/22)
Oct 17 2018 11:16:11: %ASA-6-113012: AAA user authentication Successful : local database : user = asaAdmin15
Oct 17 2018 11:16:11: %ASA-6-113008: AAA transaction status ACCEPT : user = asaAdmin15
Oct 17 2018 11:16:11: %ASA-6-611101: User authentication succeeded: IP address: 192.168.11.171, Uname: asaAdmin15
Oct 17 2018 11:16:11: %ASA-6-611101: User authentication succeeded: IP address: 192.168.11.171, Uname: asaAdmin15
Oct 17 2018 11:16:11: %ASA-6-605005: Login permitted from 192.168.11.171/57392 to inside:192.168.110.29/ssh for user "asaAdmin15"
Oct 17 2018 11:16:12: %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-611102: User authentication failed: IP address: 192.168.11.171, Uname: asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-611102: User authentication failed: IP address: 192.168.11.171, Uname: asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-611102: User authentication failed: IP address: 192.168.11.171, Uname: asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-308001: Console enable password incorrect for 3 tries (from ssh (remote 192.168.11.171))
Oct 17 2018 11:16:12: %ASA-6-113012: AAA user authentication Successful : local database : user = asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-113008: AAA transaction status ACCEPT : user = asaAdmin15
Oct 17 2018 11:16:12: %ASA-6-611101: User authentication succeeded: IP address: 192.168.11.171, Uname: asaAdmin15
Oct 17 2018 11:16:12: %ASA-5-502103: User priv level changed: Uname: asaAdmin15 From: 1 To: 15
Oct 17 2018 11:16:12: %ASA-5-111008: User 'asaAdmin15' executed the 'enable' command.
Oct 17 2018 11:16:12: %ASA-5-111008: User 'asaAdmin15' executed the 'terminal pager 0' command.
Oct 17 2018 11:16:12: %ASA-5-111010: User 'asaAdmin15', running 'CLI' from IP 192.168.11.171, executed 'terminal pager 0'
Oct 17 2018 11:17:12: %ASA-6-315011: SSH session from 192.168.11.171 on interface inside for user "*****" disconnected by SSH server, reason: "Time-out activated" (0x3c) 
Oct 17 2018 11:17:13: %ASA-5-611103: User logged out: Uname: asaAdmin15
Oct 17 2018 11:17:52: %ASA-6-302014: Teardown TCP connection 3100 for inside:192.168.11.171/57392 to identity:192.168.110.29/22 duration 0:01:40 bytes 3058024 TCP Reset-O
```

**My second question is, how can I implement periodical writing into the server even when data are still comming?**

**Comment by mscdex** [comment] 2023-12-23 03:18
Closing this for now as a lot has changed since 2015. We can reopen if there is still an issue.

**Closed by mscdex** 2023-12-23 03:18 UTC
