### ISSUE TITLE
plink command port

### ISSUE THREAD

**Issue by aberbegall** [mscdex/ssh2#595] opened 2017-08-01 08:36 UTC
Hi, I am using this nodejs script
https://github.com/novnc/websockify/blob/master/other/js/websockify.js
In order to share the screen of a machine(X11Vnc server) on a web browser. Additionally I have to execute this command to forward ports on that machine:
plink.exe -L 5900:localhost:5900 -i key.ppk user@remotehost
Can you provide some hint on how I could port the plink command into the websockify.js script using ssh2?
Thanks in advance

**Comment by mscdex** [comment] 2017-08-01 14:12
Duplicate of https://github.com/mscdex/ssh2/issues/579.

**Closed by mscdex** 2017-08-01 14:12 UTC
