### ISSUE TITLE
Test code should be excluded from the published package

### ISSUE THREAD

**Issue by lucasjvw** [mscdex/ssh2#1362] opened 2024-02-05 16:28 UTC
When downloading the ssh2 package from npm, the package includes test code and examples. In particular, test/fixtures includes some key files that are being flagged by security scan software.

Test code and fixtures should not be included in published packages

**Comment by mscdex** [comment] 2024-02-05 16:55
Duplicate of https://github.com/mscdex/ssh2/issues/1217.

**Closed by mscdex** 2024-02-05 16:55 UTC
