### ISSUE TITLE
Out of memory with fastPut

### ISSUE THREAD

**Issue by felipeaf** [mscdex/ssh2#316] opened 2015-08-28 20:02 UTC
I have a script to copy a lot of files using ssh2 sftp fastput, but i'm with a issue due to large memory consumption.

For example, in my scenario, i have a centos in a virtual machine with 512 mb ram, and node receive a SIGKILL due to out of memory when i tried to copy 231 files or more (1,1 mb each. node was in 55% of %MEM in top before die). With the scp command line (Linux tool), i've copied 1000 files with a small memory usage ( scp is using 0.3 %MEM in top command) and probably i can copy more.

For the scp test i've passed all files in the same commandline
like `scp $MYFILES destuser@desthost:destdir`

For the ssh2 test i've used that code:

```javascript

var SSHClient = require('ssh2').Client;
var fs = require("fs");
var path = require("path");

/* *********** CONFIG HERE */

var configSSH2 = {
    host: "XXX.XXX.XXX.XXX", /* CONFIG HERE */
    port: 22,
    username: 'root', /* CONFIG HERE */
    privateKey: fs.readFileSync(path.join(process.env.HOME, '.ssh/id_rsa')) /* multiplataform: require('osenv').home() */ /* CONFIG HERE */
};

/* srcDir needs to exist and to have a lot of files */ 
/* dstDir neets to exist */
var srcDir = 'PUT_LOCAL_SRC_DIR_HERE'; /* CONFIG HERE */
var dstDir = 'PUT_REMOTE_TARGET_DIR_HERE';  /* CONFIG HERE */

/* ********** END OF CONFIG PART */

var conn = new SSHClient();
conn.on('ready', function() {
    _connected = true;
    console.log("connection ready");
    
    conn.sftp(function (err,sftp) {
        if(err) {
            console.log("Error on connecting sftp", err);
            return;
        }
        runTest(sftp);
    });
    
}).on("close", function() {
    _connected = false;
    log.info("connection closed");
    self._conn.connect(configSSH2);
}).connect(configSSH2);

var count = 0;
function runTest(sftp) {
    var files = fs.readdirSync(srcDir);
    //files = files.slice(0, 231); /* uncoment to test with less files */
    files.forEach(function(file) {
        sftp.fastPut(path.join(srcDir, file), path.join(dstDir, file), function(err) {
            if(err) {
                console.log("Error when uploading", file, ":", err);
            }
            if(++count == files.length) {
                console.log("Transfer complete");
            }
        });
    });
}


```

Is this some memory leak in ssh2 module?

**Comment by mscdex** [comment] 2015-08-28 20:40
The problem is that you're transferring too much data at one time. By default, `fastPut()` performs at most 25 reads of 32KB each at any given time. So for one file transfer, there could be at most ~800KB of a file buffered in memory. Assuming that the server accepts every single file transfer simultaneously (and each file is 800KB or larger in total size), that means you could be using at most ~185MB of memory. That's not including any other memory used by the node process.

Since you only have 512MB of RAM, ~185MB is quite a lot. Here are a few ways you might solve this problem:

* Only transfer one file at a time. This is probably the best (compatible) solution, since not all servers have the same limits in place when it comes to concurrency and such. It also means you know that (by default) at most only 800KB of any file will be buffered at any given time.

* Only transfer x amount of data at a time. Since in this scenario you said all of your files are 1.1MB, which is close to the max buffer size for a file transfer (800KB with default settings), this would effectively be an "only transfer x number of files at a time."

* Override the default `concurrency` and/or `chunkSize` options used by `fastPut()`. This suggestion could be combined with either of the above two solutions to reduce memory usage further.

The reason why `scp`/`sftp` from OpenSSH does not use so much memory is that they transfer at most 64 * 32KB (2MB) at any given time. With your file set, that's almost 2 files at a time.

**Closed** 2015-10-28 18:57 UTC
