### ISSUE TITLE
sftp.createReadStream results in a stream that differs from the source file.

### ISSUE THREAD

**Issue by ace234b** [mscdex/ssh2#390] opened 2016-01-29 01:37 UTC
I have the following code. 

    sshConn.on('ready', function () {
        sshConn.sftp(function (err, sftp) {
            let sourceFile = sftp.createReadStream('/app/cdr/cdr201601290045');
            let destinationFile = fs.createWriteStream('cdr201601290045');
    
            sourceFile.pipe(destinationFile);
    
            sourceFile.on('end', function () {
                console.log('Source Ended')
            });
    
            destinationFile.on('finish', function () {
                console.log('DestinationFileFinish')
            })
        })
    });

However I encounter an odd problem. The destination file is always missing data the source file contains, and the odd part is that its not missing from the end of the file, lines are missed intermittently throughout as well as fields being missed from certain lines(It's a CSV). The destination file is always the same file size with the same lines/fields missing, it does not change when the file is downloaded again so it isnt some kind of funky transient network issue.

Further to this no errors are emitted from sourceFile.on('error').

[debug.txt](https://github.com/mscdex/ssh2/files/109157/debug.txt)

Any help in troubleshooting will be appreciated.

Note:
I cant use the fastGet() method as the end device (An embedded system running VXWorks) does not support fstat(), only stat().

**Comment by mscdex** [comment] 2016-01-29 04:52
Does `fastGet()` work if you replace the `fstat()` usage with `stat()`?

**Comment by ace234b** [comment] 2016-01-29 05:41
Yes it does. Any ideas on what causes the odd behaviour with streams?

**Comment by ddsol** [comment] 2016-03-04 16:04
Setting the high water mark very low fixes this for me, but it's terribly slow. There's a definite bug somewhere. Something with the pool management, probably.

**Comment by mscdex** [comment] 2016-03-04 16:23
@ddsol `sftp.createReadStream()` will always be slow compared to `fastGet()` because the former only has 1 outstanding read at any given time, whereas the latter does parallel reads.

**Comment by ddsol** [comment] 2016-03-04 16:26
It slows down when lowering the `highWaterMark`. So in order to get the `createReadStream` stream to work correctly, you have to lower the `highWaterMark`, which is not without penalty: It slows the stream. The point is not to compare to `fastGet`, but to a higher `highWaterMark` which would be preferable if it weren't for the fact that it corrupts the stream (at least when piping).

**Comment by mscdex** [comment] 2016-03-05 04:34
@ace234b @ddsol The file stream implementations are just about copied verbatim from node's `fs` streams. I just tested with master with varying file sizes and could not duplicate the issue.

**Comment by ddsol** [comment] 2016-03-05 04:44
Try a large file and use `.pipe ()`. I haven't seen a single transfer succeed.

My app streams images from my Galaxy phone to the browser and the header is always fine followed by major corruption of the image. I pipe directly to the response object and use latest stable node and plain http (no express). Visually it looks like it skips large blocks.

From the original issue it looks to be `pipe ()` that brings on the issue. I'll see if can just fix it when I have some time.

**Comment by mscdex** [comment] 2016-03-05 05:03
@ddsol I tried with a 240mb file, a 5mb file, a 1mb file, and a 128kb file.

**Comment by ddsol** [comment] 2016-03-05 05:07
So maybe it's a timing issue. Could be difficult to reproduce. The Galaxy may be slow, causing the issue. I couldn't say. However I get successful transfers only after setting the high water mark to 32768 or lower.

As I said, I'll probably work on fixing it myself. It's so much easier to fix a problem you can repro :).

**Comment by ace234b** [comment] 2016-03-05 05:25
I could only ever produce it on a specific device (An Oracle NetNet). It works perfectly on other devices.

**Comment by mscdex** [comment] 2016-07-30 22:02
Closing this for now. If someone can provide a reproducible example, even if it means providing access to a specific host for testing purposes, let me know.

**Closed by mscdex** 2016-07-30 22:02 UTC

**Comment by mohammedamzads** [comment] 2018-09-07 06:10
I am able to reproduce the issue, for createReadStream having a lower highWaterMark seems to have a fix however slowing the download process.
