### ISSUE TITLE
Read streams appear to drop data

### ISSUE THREAD

**Issue by justinmchase** [mscdex/ssh2#739] opened 2018-10-11 14:00 UTC
I have this very simple script for downloading files using the `sftp.createReadStream` api in this library but the downloaded file is broken, sections of bytes are missing from it.

When I download the file any other way the file is as expected. Here is an example script I am using to download via`sftp.createReadStream`:

```js
import 'babel-polyfill'
import fs from 'fs'
import { Client } from 'ssh2'

const config = {
  host: 'example.brickftp.com', 
  username: 'example', 
  password: '...' 
}
const client = new Client()
const file = 'example.csv'

function error (err) {
  console.log(err)
  process.exit(1)
}

client.on('error', error)
client.on('ready', () => {
  client.sftp((err, sftp) => {
    if (err) return error(err)
    console.log('downloading...')
    sftp
      .createReadStream(file)
      .on('error', error)
      .pipe(fs.createWriteStream(`${process.env.HOME}/Downloads/remote.csv`, 'utf8'))
      .on('error', error)
      .on('close', () => {
        console.log('done.')
        client.end()
      })
  })
})
client.connect(config)
```

The differences between the original file and the downloaded file using this script appear at two places in my file where the it seems that the chunks are stitched back together, there is a section of bytes missing from the downloaded file at each of these positions.

However, if I download the file, still using this library but instead using the `sftp.open` and `sftp.read` api's then it works perfectly:

```js
import 'babel-polyfill'
import fs from 'fs'
import { Client } from 'ssh2'

const config = {
  host: 'example.brickftp.com', 
  username: 'example', 
  password: '...' 
}
const client = new Client()
const file = 'example.csv'

function error (err) {
  console.log(err)
  process.exit(1)
}

function download(sftp, callback) {
  sftp.open(file, 'r', function (err, handle) {
    if (err) return callback(err)
    sftp.fstat(handle, function (err, stat) {
      if (err) return callback(err)
      console.log('stat:', stat)
      var bytes = stat.size
      var buffer = Buffer.alloc(bytes)
      if (bytes === 0) return callback(null, buffer)
      buffer.fill(0)
      var cb = function (err, readBytes, offset, position) {
        if (err) return callback(err)
        position = position + readBytes
        bytes = bytes - readBytes
        if (bytes < 1) {
          sftp.close(handle, err => callback(err, buffer))
        } else {
          sftp.read(handle, buffer, position, bytes, position, cb)
        }
      }
      sftp.read(handle, buffer, 0, bytes, 0, cb)
    })
  })
}

client.on('error', error)
client.on('ready', () => {
  client.sftp((err, sftp) => {
    if (err) return error(err)
    console.log('downloading...')
    download(sftp, (err, buff) => {
      if (err) return error(err)
      fs.writeFileSync(`${process.env.HOME}/Downloads/remote.csv`, buff, 'utf8')
      client.end()
      console.log('end.')
    })
  })
})
client.connect(config)
```

It is then successful. This tells me that there is most likely an issue in the ReadStream created by the `createReadStream` api specifically.

**Comment by kabo** [comment] 2018-10-30 01:11
I'm also experiencing this issue with `createReadStream`

**Comment by eventEmitter** [comment] 2018-11-07 12:29
it may help if you set the high water mark to `65535` in the options object:

```javascript
sftp.createReadStream(file, {
     highWaterMark: 65535,
})
```

source: https://github.com/jyu213/ssh2-sftp-client/issues/37#issue-264708529

**Comment by justinmchase** [comment] 2018-11-07 19:09
@eventEmitter That issue makes me think there is an off-by-one error somewhere, does that fix the issue or is it a work around that somehow fixes it some of the time?

**Comment by mofux** [comment] 2018-11-07 20:09
Until now we always failed to reproduce / debug this problem (see https://github.com/mscdex/ssh2-streams/pull/42). If you can provide some example code against a public sftp server that would definitely help.

**Comment by eventEmitter** [comment] 2018-11-08 13:56
@justinmchase i had the problem when i was using the jyu213/ssh2-sftp-client module. The workaround did solve the issue for me. Sadly i don't have that code anymore. I used a docker image as server: https://hub.docker.com/r/atmoz/sftp/

@mofux I just implemented a sftp client based on the ssh2 module myself, i never ran into this issue again. I tried to reproduce it without success.

**Comment by justinmchase** [comment] 2018-11-08 16:56
Ok, I'm attaching a 100% reproduction of this issue for you.

I tried to reproduce this by using a local docker container and even doing mass downloads to try to simulate network traffic but could not. Even with 1000 concurrent download the totally local reproduction always worked correctly.

So instead I just created a test account in brickftp with access to only one file exactly and tried that and it fails 100% of the time for me so far. I'm attaching the full code sample, which has a copy of the file that I uploaded to brickftp for comparison.

## Repro
unzip the example code and cd into the directory
```js
npm i
npm start

> sftp-bug@1.0.0 start /Users/justin/code/sftp-bug
> node -r babel-register .

downloading...
NOT the same!
```

[sftp-bug-1.0.0.tar.gz](https://github.com/mscdex/ssh2/files/2562696/sftp-bug-1.0.0.tar.gz)

**Comment by mofux** [comment] 2018-11-08 19:38
@justinmchase Thanks for this, I can reproduce the problem reliably (I've got in contact with the BrickFTP support, they gave me a free test account and seem to be very supportive getting this issue fixed, as they also had node-ssh2 users complaining).

I've tried to reproduce this with the OpenSSH sftp client using a custom buffer size of `64*1024` (by default its `32*1024` as stated in their man pages here: https://man.openbsd.org/sftp), but it downloads the file correctly with the correct size:
```bash
sftp -B 65536 user@.... 
```
Feels like there's something wrong with the createReadStream implementation that only gets triggered with certain server implementations...

@mscdex Why did you decide to use `64*1024` as the highWaterMark in the first place? The writeStream highWaterMark defaults to `32*1024` 🤔

**Comment by mscdex** [comment] 2018-11-08 19:58
@mofux It's copied from node's `fs.ReadStream` implementation.

**Comment by justinmchase** [comment] 2018-11-08 20:45
> triggered with certain server implementations...

I agree this is likely, the exact same code running locally in docker had no problem at all. I suppose its possible that brick has an issue on their side actually... I am imagining that the ssh2 read stream is doing some requests for chunks in parallel? It could be that the server is literally mixing them up and giving bogus responses.

The solution I had above in the original document was to essentially read each chunk of the file in series, that works. So there very well could be some kind of parallelism related issue with brick (and/or other servers) specifically.

## Timeline
Also, to add some additional information I will say that this came up for me because we had an automated process that had been running fine for a long time and then suddenly stopped working, after digging for a long time this ended up being the issue. But I have some times that may be relevant for you or for BrickFTP to help isolate possible changes:

* `Friday, September 7th 2018, 3:00:20am` the readStream to BrickFTP was working.
* `Saturday, September 8th 2018, 3:00:25am` the readStream to BrickFTP stopped working.

So sometime between those two times its possible there was some kind of change that caused it to stop working.

**Comment by mscdex** [comment] 2018-11-08 21:05
With streams there are no parallel requests, which is why they are slower than the `sftp.fast*()` methods (which *do* employ parallel requests).

**Comment by mofux** [comment] 2018-11-09 02:17
I've been running some tests and it seems that at least the BrickFTP server's highest working highWaterMark is `63*1000`. I've been logging the chunks that arrive on the sftp readStream and their sizes like this:

```javascript
sftp
	.createReadStream(remoteFile, { highWaterMark: 63 * 1024 })
	.on('data', (data) => console.log('chunk', count++, data.length))
```

*Test 1 (good): highWaterMark = 63 * 1024 - 1 (64511)*
```bash
chunk 0 64511                                                                                                                                                                                                                
chunk 1 64511                                                                                                                                                                                                                
chunk 2 64511                                                                                                                                                                                                                
chunk 3 64511                                                                                                                                                                                                                
chunk 4 64511                                                                                                                                                                                                                
chunk 5 64511                                                                                                                                                                                                                
chunk 6 64511                                                                                                                                                                                                                
chunk 7 64511                                                                                                                                                                                                                
chunk 8 64511                                                                                                                                                                                                                
chunk 9 64511                                                                                                                                                                                                                
chunk 10 64511                                                                                                                                                                                                               
chunk 11 64511                                                                                                                                                                                                               
chunk 12 64511                                                                                                                                                                                                               
chunk 13 64511                                                                                                                                                                                                               
chunk 14 64511                                                                                                                                                                                                               
chunk 15 64511                                                                                                                                                                                                               
chunk 16 64511                                                                                                                                                                                                               
chunk 17 64511                                                                                                                                                                                                               
chunk 18 64511                                                                                                                                                                                                               
chunk 19 64511                                                                                                                                                                                                               
chunk 20 64511                                                                                                                                                                                                               
chunk 21 64511                                                                                                                                                                                                               
chunk 22 64511                                                                                                                                                                                                               
chunk 23 64511                                                                                                                                                                                                               
chunk 24 64511                                                                                                                                                                                                               
chunk 25 64511                                                                                                                                                                                                               
chunk 26 64511                                                                                                                                                                                                               
chunk 27 64511                                                                                                                                                                                                               
chunk 28 64511                                                                                                                                                                                                               
chunk 29 64511                                                                                                                                                                                                               
chunk 30 64511                                                                                                                                                                                                               
chunk 31 64511                                                                                                                                                                                                               
chunk 32 64511                                                                                                                                                                                                               
chunk 33 64511                                                                                                                                                                                                               
chunk 34 64511                                                                                                                                                                                                               
chunk 35 64511                                                                                                                                                                                                               
chunk 36 64511                                                                                                                                                                                                               
chunk 37 64511                                                                                                                                                                                                               
chunk 38 64511                                                                                                                                                                                                               
chunk 39 64511                                                                                                                                                                                                               
chunk 40 64511                                                                                                                                                                                                               
chunk 41 64511                                                                                                                                                                                                               
chunk 42 64511                                                                                                                                                                                                               
chunk 43 64511                                                                                                                                                                                                               
chunk 44 64511                                                                                                                                                                                                               
chunk 45 64511                                                                                                                                                                                                               
chunk 46 64511                                                                                                                                                                                                               
chunk 47 64511                                                                                                                                                                                                               
chunk 48 64511                                                                                                                                                                                                               
chunk 49 64511                                                                                                                                                                                                               
chunk 50 64511                                                                                                                                                                                                               
chunk 51 64511                                                                                                                                                                                                               
chunk 52 64511                                                                                                                                                                                                               
chunk 53 64511                                                                                                                                                                                                               
chunk 54 64511                                                                                                                                                                                                               
chunk 55 64511                                                                                                                                                                                                               
chunk 56 64511                                                                                                                                                                                                               
chunk 57 64511                                                                                                                                                                                                               
chunk 58 64511                                                                                                                                                                                                               
chunk 59 64511                                                                                                                                                                                                               
chunk 60 64511                                                                                                                                                                                                               
chunk 61 64511                                                                                                                                                                                                               
chunk 62 64511                                                                                                                                                                                                               
chunk 63 64511                                                                                                                                                                                                               
chunk 64 64511                                                                                                                                                                                                               
chunk 65 64511                                                                                                                                                                                                               
chunk 66 64511                                                                                                                                                                                                               
chunk 67 64511                                                                                                                                                                                                               
chunk 68 64511                                                                                                                                                                                                               
chunk 69 64511                                                                                                                                                                                                               
chunk 70 64511                                                                                                                                                                                                               
chunk 71 64511                                                                                                                                                                                                               
chunk 72 64511                                                                                                                                                                                                               
chunk 73 64511                                                                                                                                                                                                               
chunk 74 64511                                                                                                                                                                                                               
chunk 75 64511                                                                                                                                                                                                               
chunk 76 64511                                                                                                                                                                                                               
chunk 77 37652                                                                                                                                                                                                               
---
Data events:  78                                                                                                                                                                                                             
original: 5004999, downloaded: 5004999  
```

*Test 2 (good): highWaterMark = 63 * 1024 (64512)*
```bash
chunk 0 64512                                                                                                                                                                                                                
chunk 1 64512                                                                                                                                                                                                                
chunk 2 64512                                                                                                                                                                                                                
chunk 3 64512                                                                                                                                                                                                                
chunk 4 64512                                                                                                                                                                                                                
chunk 5 64512                                                                                                                                                                                                                
chunk 6 64512                                                                                                                                                                                                                
chunk 7 64512                                                                                                                                                                                                                
chunk 8 64512                                                                                                                                                                                                                
chunk 9 64512                                                                                                                                                                                                                
chunk 10 64512                                                                                                                                                                                                               
chunk 11 64512                                                                                                                                                                                                               
chunk 12 64512                                                                                                                                                                                                               
chunk 13 64512                                                                                                                                                                                                               
chunk 14 64512                                                                                                                                                                                                               
chunk 15 64512                                                                                                                                                                                                               
chunk 16 64512                                                                                                                                                                                                               
chunk 17 64512                                                                                                                                                                                                               
chunk 18 64512                                                                                                                                                                                                               
chunk 19 64512                                                                                                                                                                                                               
chunk 20 64512                                                                                                                                                                                                               
chunk 21 64512                                                                                                                                                                                                               
chunk 22 64512                                                                                                                                                                                                               
chunk 23 64512                                                                                                                                                                                                               
chunk 24 64512                                                                                                                                                                                                               
chunk 25 64512                                                                                                                                                                                                               
chunk 26 64512                                                                                                                                                                                                               
chunk 27 64512                                                                                                                                                                                                               
chunk 28 64512                                                                                                                                                                                                               
chunk 29 64512                                                                                                                                                                                                               
chunk 30 64512                                                                                                                                                                                                               
chunk 31 64512                                                                                                                                                                                                               
chunk 32 64512                                                                                                                                                                                                               
chunk 33 64512                                                                                                                                                                                                               
chunk 34 64512                                                                                                                                                                                                               
chunk 35 64512                                                                                                                                                                                                               
chunk 36 64512                                                                                                                                                                                                               
chunk 37 64512                                                                                                                                                                                                               
chunk 38 64512                                                                                                                                                                                                               
chunk 39 64512                                                                                                                                                                                                               
chunk 40 64512                                                                                                                                                                                                               
chunk 41 64512                                                                                                                                                                                                               
chunk 42 64512                                                                                                                                                                                                               
chunk 43 64512                                                                                                                                                                                                               
chunk 44 64512                                                                                                                                                                                                               
chunk 45 64512                                                                                                                                                                                                               
chunk 46 64512                                                                                                                                                                                                               
chunk 47 64512                                                                                                                                                                                                               
chunk 48 64512                                                                                                                                                                                                               
chunk 49 64512                                                                                                                                                                                                               
chunk 50 64512                                                                                                                                                                                                               
chunk 51 64512                                                                                                                                                                                                               
chunk 52 64512                                                                                                                                                                                                               
chunk 53 64512                                                                                                                                                                                                               
chunk 54 64512                                                                                                                                                                                                               
chunk 55 64512                                                                                                                                                                                                               
chunk 56 64512                                                                                                                                                                                                               
chunk 57 64512                                                                                                                                                                                                               
chunk 58 64512                                                                                                                                                                                                               
chunk 59 64512                                                                                                                                                                                                               
chunk 60 64512                                                                                                                                                                                                               
chunk 61 64512                                                                                                                                                                                                               
chunk 62 64512                                                                                                                                                                                                               
chunk 63 64512                                                                                                                                                                                                               
chunk 64 64512                                                                                                                                                                                                               
chunk 65 64512                                                                                                                                                                                                               
chunk 66 64512                                                                                                                                                                                                               
chunk 67 64512                                                                                                                                                                                                               
chunk 68 64512                                                                                                                                                                                                               
chunk 69 64512                                                                                                                                                                                                               
chunk 70 64512                                                                                                                                                                                                               
chunk 71 64512                                                                                                                                                                                                               
chunk 72 64512                                                                                                                                                                                                               
chunk 73 64512                                                                                                                                                                                                               
chunk 74 64512                                                                                                                                                                                                               
chunk 75 64512                                                                                                                                                                                                               
chunk 76 64512                                                                                                                                                                                                               
chunk 77 37575 
---
Data events:  78                                                                                                                                                                                                             
original: 5004999, downloaded: 5004999
```

*Test 3 (bad): highWaterMark = 63 * 1024 + 1 (64513)*

```bash
chunk 0 64512                                                                                                                                                                                                                
chunk 1 64512                                                                                                                                                                                                                
chunk 2 64512                                                                                                                                                                                                                
chunk 3 64512                                                                                                                                                                                                                
chunk 4 64512                                                                                                                                                                                                                
chunk 5 64512                                                                                                                                                                                                                
chunk 6 64512                                                                                                                                                                                                                
chunk 7 64512                                                                                                                                                                                                                
chunk 8 64512                                                                                                                                                                                                                
chunk 9 64512                                                                                                                                                                                                                
chunk 10 64512                                                                                                                                                                                                               
chunk 11 64512                                                                                                                                                                                                               
chunk 12 64512                                                                                                                                                                                                               
chunk 13 64512                                                                                                                                                                                                               
chunk 14 64512                                                                                                                                                                                                               
chunk 15 64512                                                                                                                                                                                                               
chunk 16 64512                                                                                                                                                                                                               
chunk 17 64512                                                                                                                                                                                                               
chunk 18 64512                                                                                                                                                                                                               
chunk 19 64512                                                                                                                                                                                                               
chunk 20 64512                                                                                                                                                                                                               
chunk 21 64512                                                                                                                                                                                                               
chunk 22 64512                                                                                                                                                                                                               
chunk 23 64512                                                                                                                                                                                                               
chunk 24 64512                                                                                                                                                                                                               
chunk 25 64512                                                                                                                                                                                                               
chunk 26 64512                                                                                                                                                                                                               
chunk 27 64512                                                                                                                                                                                                               
chunk 28 64512                                                                                                                                                                                                               
chunk 29 64512                                                                                                                                                                                                               
chunk 30 64512                                                                                                                                                                                                               
chunk 31 64512                                                                                                                                                                                                               
chunk 32 64512                                                                                                                                                                                                               
chunk 33 64512                                                                                                                                                                                                               
chunk 34 64512                                                                                                                                                                                                               
chunk 35 64512                                                                                                                                                                                                               
chunk 36 64512                                                                                                                                                                                                               
chunk 37 64512                                                                                                                                                                                                               
chunk 38 64512                                                                                                                                                                                                               
chunk 39 64512                                                                                                                                                                                                               
chunk 40 64512                                                                                                                                                                                                               
chunk 41 64512                                                                                                                                                                                                               
chunk 42 64512                                                                                                                                                                                                               
chunk 43 64512                                                                                                                                                                                                               
chunk 44 64512                                                                                                                                                                                                               
chunk 45 64512                                                                                                                                                                                                               
chunk 46 64512                                                                                                                                                                                                               
chunk 47 64512                                                                                                                                                                                                               
chunk 48 64512                                                                                                                                                                                                               
chunk 49 64512                                                                                                                                                                                                               
chunk 50 64512                                                                                                                                                                                                               
chunk 51 64512                                                                                                                                                                                                               
chunk 52 64512                                                                                                                                                                                                               
chunk 53 64512                                                                                                                                                                                                               
chunk 54 64512                                                                                                                                                                                                               
chunk 55 64512                                                                                                                                                                                                               
chunk 56 64512                                                                                                                                                                                                               
chunk 57 64512                                                                                                                                                                                                               
chunk 58 64512                                                                                                                                                                                                               
chunk 59 64512                                                                                                                                                                                                               
chunk 60 64512                                                                                                                                                                                                               
chunk 61 64512                                                                                                                                                                                                               
chunk 62 64512                                                                                                                                                                                                               
chunk 63 64512                                                                                                                                                                                                               
chunk 64 64512                                                                                                                                                                                                               
chunk 65 64512                                                                                                                                                                                                               
chunk 66 64512                                                                                                                                                                                                               
chunk 67 64512                                                                                                                                                                                                               
chunk 68 64512                                                                                                                                                                                                               
chunk 69 64512                                                                                                                                                                                                               
chunk 70 64512                                                                                                                                                                                                               
chunk 71 64512                                                                                                                                                                                                               
chunk 72 64512                                                                                                                                                                                                               
chunk 73 64512                                                                                                                                                                                                               
chunk 74 64512                                                                                                                                                                                                               
chunk 75 64512                                                                                                                                                                                                               
chunk 76 64512                                                                                                                                                                                                               
chunk 77 37498                           
---                                                                                                                                                                                    
Data events:  78                                                                                                                                                                                                             
original: 5004999, downloaded: 5004922 
```

The first two examples worked without corruption, the third example obviously has the following problems: 

- The buffer received with the streams `data` event had a length of `63 * 1024 (64512)`, although we requested a chunk to have the size of `63 * 1024 + 1 (64513)`.
- The total received bytes where 77 bytes short of the original file, which is obviously is one missing byte for every *filled* data chunk.

**Comment by justinmchase** [comment] 2018-11-09 19:11
Is that something ssh2 can correct for or are you saying brickftp is actually sending bogus data?

**Comment by mofux** [comment] 2018-11-09 23:48
There seems to be a difference between the content length we expect to see, and the content length sent in the reply of the server. 

`dataLen` is the amount of bytes we've read from the server response, and `reqBufLen` is the length of our buffer (equals highWaterMark):
<img width="1914" alt="screenshot 2018-11-09 at 20 53 54" src="https://user-images.githubusercontent.com/2785983/48293681-96197e00-e480-11e8-925d-e8e9b144c4f7.png">

The response length is extracted here, I've expanded the response buffer's structure that seem to hold the information about the length of the response:
<img width="1439" alt="screenshot 2018-11-10 at 00 39 31" src="https://user-images.githubusercontent.com/2785983/48293818-22c43c00-e481-11e8-84e4-d25ada9d04d9.png">

Let's crunch numbers:
```
    return buf[offset++] * 16777216
           + buf[offset++] * 65536
           + buf[offset++] * 256
           + buf[offset];
```
with the variables of that packet, where `offset` was 4:
0 * 16777216 + 0 * 65536 + 252 * 256 + 0 = 64512

So imho the server reponds with the incorrect size... 🤔

@mscdex From looking at the data, what do you think?

**Comment by justinmchase** [comment] 2018-11-28 14:53
@mofux Would it be possible to use the actual size from the server rather than assume the server is going to always respond with the correct size?

**Comment by liximomo** [comment] 2019-01-20 01:36
I'm also experiencing this issue with `createReadStream`.

**Comment by rgalapate** [comment] 2019-01-25 09:00
Data seems to be dropped too in `createWriteStream`

**Comment by mscdex** [comment] 2019-07-08 07:01
Anyone who is still having these issues, can you please try with the current `ssh2-streams` master branch? I've just updated the stream code to match node's current `fs` stream behavior/implementation.

**Comment by justinmchase** [comment] 2019-07-15 19:42
I'm running with a workaround in prod, which I'm afraid to touch for now. But I promise next time I'm in there I'll give it a try and will update here.

**Comment by kjvalencik** [comment] 2019-07-30 15:34
@mscdex The latest `ssh2-streams` did not fix it for me. The bug appears to happen when the SFTP server returns fewer bytes than requested.

**Comment by switz** [comment] 2019-09-11 04:29
Hmm, I'm also seeing a similar issue with BrickFTP servers (now called files.com) on large `fastPut` files. https://github.com/theophilusx/ssh2-sftp-client/issues/143#issuecomment-530082714

**Comment by mscdex** [comment] 2019-09-11 05:11
Is there some way I can get a (new) BrickFTP account to test/debug this?

**Comment by switz** [comment] 2019-09-11 05:16
> Is there some way I can get a (new) BrickFTP account to test/debug this?

It looks like they offer a 1 month free trial: https://app.files.com/signup/welcome

Let me know if that doesn't work for you and I'll happy debug or write some tests myself to get to the bottom of it.

Just don't forget to cancel the trial since the product is a bit pricy.

**Comment by mscdex** [comment] 2019-09-11 05:54
I just tested that example with a non-BrickFTP server and the file transferred fine every time and sha1sums matched on both sides. Even tried different node versions.

I guess I will wait to hear back from the BrickFTP folks.

**Comment by theophilusx** [comment] 2019-09-11 08:13
@mscdex I'm the new maintainer for ssh2-sftp-client. I can also confirm that I have had no errors with other sites using multiple node versions (8.x, 10, 12.x). I also have checksums which are all good, so it does seem likely this is BRICKftp specific. I don't have a BRICKftp account, but if there is anything I can do to assist, let me know.

**Closed** 2019-09-14 19:27 UTC
Labels: need more info
