### ISSUE TITLE
When i ever i send a same URL for multiple times ssh connection is opening for multiple times 

### ISSUE THREAD

**Issue by sriramulavinaykumar** [mscdex/ssh2#575] opened 2017-06-08 13:05 UTC
if(TC==='start')
       {
      console.log('after start'+TC);
        conn.on('ready', function() {

            console.log('Client :: ready');
            conn.shell('start', function(err, stream) {
                console.log("heyyyyyyyyyy"+count);
                stream.write('start>temp.log& \n');
                if (err) throw err;
                stream.on('close', function(code, signal) {
                    console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                    conn.end();
                }).on('data', function(data) {
                   res.end();
                }).stderr.on('data', function(data) {
                    console.log('STDERR: ' + data);
                });
            });
        }).connect({
            host: '127.0.0.1',
            port: 22,
            username: 'admin',
            password: 'admin'
        });  } });

**Comment by mscdex** [comment] 2017-06-08 16:08
This seems to be a duplicate of https://github.com/mscdex/ssh2/issues/576.

**Closed by mscdex** 2017-06-08 16:08 UTC
