### ISSUE TITLE
Getting assertion error when running ssh2 server example

### ISSUE THREAD

**Issue by Shachar1** [mscdex/ssh2#319] opened 2015-09-04 14:39 UTC
assert.js:86
  throw new assert.AssertionError({
AssertionError: 0 == true

few details - the error is when utils.genPublicKey is being called. 
I'm using Putty to generate my public/private ssh keys.
OS - windows.
Node version - 0.12.2
Thanks

**Comment by mscdex** [comment] 2015-09-04 16:14
Can you provide a complete, reproducible example?

**Comment by Shachar1** [comment] 2015-09-04 16:36
I took the code from Server Examples in https://github.com/mscdex/ssh2
The exception is in this line:  
var pubKey = utils.genPublicKey(utils.parseKey(fs.readFileSync('user.pub')));

I've used this guide to generate public and private keys - https://www.siteground.com/kb/how_to_generate_an_ssh_key_on_windows_using_putty/

**Comment by mscdex** [comment] 2015-10-28 05:12
I'm not able to reproduce this. If you can send me a *valid* (unused) key that causes the error I would be glad to try it out.

**Comment by Shachar1** [comment] 2015-10-28 10:06
Hey, I've attached a key that was generated from puttygen.exe that causing this error. (changed the file type to png so i can upload it...).
I've already solved this problem by using another method to create the key.
![puttypubkey](https://cloud.githubusercontent.com/assets/12940073/10785348/374dad7a-7d6c-11e5-9f00-6769404bccf9.png)

**Comment by mscdex** [comment] 2015-10-28 18:48
Thanks for the key. This should now be fixed in 767413f2a6.

**Closed by mscdex** 2015-10-28 18:48 UTC
