### ISSUE TITLE
Inconsistent behaviour with openssh server on windows 10

### ISSUE THREAD

**Issue by theophilusx** [mscdex/ssh2#1044] opened 2021-08-02 07:20 UTC
The following occurs with the ssh2 1.2.0 version (node 16.5.0).

This is a slightly odd one and I'm not sure if the problem is due to the implementation of openssh on windows. I'm testing my module against an openssh server on windows 10. When testing against an openssh server on Linux, everything works as expected. However, under windows, the code just hangs indefinitely. 

The code in question is a simple function which will append a buffer of data to a file on the sftp server. The code opens a writeStream using sftp.createWriteStream(). I have listeners attached to the error and finish events e.g. 

````js
          options.flags = 'a';
          let stream = this.sftp.createWriteStream(remotePath, options);
          stream.on('error', (err) => {
            reject(
              fmtError(`${err.message} ${remotePath}`, 'append', err.code)
            );
          });
          stream.on('finish', () => {
            resolve(`Appended data to ${remotePath}`);
          });
          if (input instanceof Buffer) {
            stream.end(input);
          } else {
            input.pipe(stream);
          }
````
The problem arises when the supplied remote path is to a directory. Under Linux, this will cause an error to be raised and all works as expected. However, with the windows based server, no error is raised and no finish event is fired. As a result, the promise which wraps the above code never gets fulfilled and the script hangs. 

When I look at the debug output I see the following

````
{"message":"Outbound: Sending CHANNEL_DATA (r:0, 66)","level":"debug"}
{"message":"SFTP: Outbound: Buffered OPEN","level":"debug"}
{"message":"Inbound: CHANNEL_DATA (r:0, 17)","level":"debug"}
{"message":"SFTP: Inbound: Received HANDLE (id:41)","level":"debug"}
{"message":"Outbound: Sending CHANNEL_DATA (r:0, 25)","level":"debug"}
{"message":"SFTP: Outbound: Buffered FSETSTAT","level":"debug"}
{"message":"Inbound: CHANNEL_DATA (r:0, 28)","level":"debug"}
{"message":"SFTP: Inbound: Received STATUS (id:42, 0, \"Success\")","level":"debug"}
{"message":"Outbound: Sending CHANNEL_DATA (r:0, 17)","level":"debug"}
{"message":"SFTP: Outbound: Buffered FSTAT","level":"debug"}
{"message":"Inbound: CHANNEL_DATA (r:0, 41)","level":"debug"}
{"message":"SFTP: Inbound: Received ATTRS (id:43)","level":"debug"}
{"message":"Outbound: Sending CHANNEL_DATA (r:0, 44)","level":"debug"}
{"message":"SFTP: Outbound: Sent WRITE (id:44)","level":"debug"}
{"message":"Inbound: CHANNEL_DATA (r:0, 28)","level":"debug"}
{"message":"SFTP: Inbound: Received STATUS (id:44, 4, \"Failure\")","level":"debug"}
{"message":"Outbound: Sending CHANNEL_DATA (r:0, 17)","level":"debug"}
{"message":"SFTP: Outbound: Buffered CLOSE","level":"debug"}
{"message":"Inbound: CHANNEL_DATA (r:0, 28)","level":"debug"}
{"message":"SFTP: Inbound: Received STATUS (id:45, 0, \"Success\")","level":"debug"}
````
The last 5 lines seem to be the interesting ones. The first one seems to indicate that a failure status was returned, then the buffer is closed and a 'success' status is returned. 

What I don't understand is -

why is the failure status not reported/picked up anywhere?
why are no finish or error events being fired? 

I could work around this issue by first checking to see that the target path is a file and not a directory via a call to stat, but would prefer to avoid that additional command if possible - especially given this is not required under a server running on Linux. 

Is this just a bit of weirdness with an openssh server running under windows or is it perhaps something not being handled correctly by ssh2 when interacting with windows?

In case it is also relevant, I've also observed that the windows server seems to generate multiple errors for one base error. For example, when trying to connect, if you provide a bad username or password, you first get an error stating that all authentication methods have failed, but then you also get a conneciton reset by peer error. Again, not sure if this is a quirk of the Windows platform or if it might be related to the error we saw a while back where multiple errors were being raised for a single error?

**Comment by mscdex** [comment] 2021-08-02 15:20
There is nothing platform-specific going on. I cannot reproduce the issue in a test with the same sequence of events (open successful, write failed, close successful).

**Comment by theophilusx** [comment] 2021-08-02 16:13
Is this with an openssh sftp server on the windows box and if so, what
version?

I'm running SSH-2.0-OpenSSH_for_Windows_8.1, which is what comes with
windows 10. Client is running on a Linux host. 

I believe this code was working when running ssh2 0.8.9, but tomorrow
I'll downgrade and verify.

**Comment by mscdex** [comment] 2021-08-02 16:17
I'm referring to a unit test.

**Comment by theophilusx** [comment] 2021-08-02 22:54
OK. This issue only occurs when connecting to an sftp server running on
Windows 10. The same code works fine when the server you are connecting
to is running on Linux or macOS.

I will put together a minimal reproducible example and provide some data
for comparison.

**Comment by mscdex** [comment] 2021-08-03 03:40
> OK. This issue only occurs when connecting to an sftp server running on Windows 10. The same code works fine when the server you are connecting to is running on Linux or macOS.

Right, however at least for me the sequence of events is different for Linux, where it fails on the open, not the write. I just find it strange that duplicating the same series of events as shown in your debug output in a unit test does not trigger the issue you're reporting.

**Comment by theophilusx** [comment] 2021-08-03 11:11
Attached are 3 files -

append.js.txt - an script using ssh2 to append data to a file on a remote sftp server. The script needs to be called with the path to the remote 'object'. If the remote object does not exist or is a file, all works fine. If it is a path to a directory, it generates a 'Failure' error when the server is on Linux. If the server is on windows, it just hangs indefinitely.

debug-linuxServer.log.txt - this is the debug output from calling the above script with an argument which is a path to a directory on the remote server. 

debug-windowsServer.log.txt - the debug log with the script being called with the same argument as with the linux server. The script just hangs and never exits - no events fired and no errors thrown.

Hope the two debug logs can help identify why there is this difference between servers. I also ran the script against a macOS (Big Sur) and it worked as expected (same as for Linux based server).  

[append.js.txt](https://github.com/mscdex/ssh2/files/6923594/append.js.txt)
[debug-linuxServer.log](https://github.com/mscdex/ssh2/files/6923597/debug-linuxServer.log)
[debug-windowsServer.log](https://github.com/mscdex/ssh2/files/6923599/debug-windowsServer.log)

**Comment by mscdex** [comment] 2021-08-07 16:14
The logs you've provided don't show anything different than what we've already seen. I don't have a Windows server to test with and like I said a unit test with the exact same order of events as happens on the Windows server (according to your debug output) does not duplicate the issue so I don't know what else I can do.

**Comment by theophilusx** [comment] 2021-08-08 03:24
I don't know either.

I guess there is a chance that if the windows server is doing something
different/odd, it may not be logged and so may not be in the log output.
However, I'm not a Windows user, so a bit out of my depth as well. I
only tripped over this issue when trying to track down a different issue
logged by an ssh2-sftp-client user. I have worked around the issue in
ssh2-sftp-client by adding additional test to verify the target is a
file. Downside is another sftp request - upside is much better error
message than 'Failure' and no hanging.

I guess the only thing possible now is to leave the issue open and hope
someone who is a Windows user either encounters the same issue or can
reproduce the issue (which would at least validate it as a real issue).

In the meantime, I'll try to find someone who is a Windows user and see
if they can run my test script. Perhaps they can provide more info and
at least confirm it is not a local issue. I might try digging into
things a bit more as well - I just find anything to do with Windows
incredibly frustrating and confusing!

**Comment by mscdex** [comment] 2023-12-23 03:04
Closing this out for now until there is a way for me to reproduce this.

**Closed by mscdex** 2023-12-23 03:04 UTC
